### ISSUE TITLE
1.2.0 Support

### ISSUE THREAD

**Issue by MirayXS** [CJBok/Cheat-Tables#1]
# V1.2.0 Support
### Animal Crossing: New Horizons
Updated My Animal Crossing New Horizons To 1.2.0, But Now The CT File Doesn't Work Anymore. 

#### Could You add Support For V1.2.0?

**Comment by MirayXS** [comment]
> You Could Add The New V1.2.0 Items Too! 
> ##### Keep Up The Good Work 👍 

###### [statues.txt](https://github.com/CJBok/Cheat-Tables/files/4530469/statues.txt)
###### [paintings.txt](https://github.com/CJBok/Cheat-Tables/files/4530470/paintings.txt)

**Comment by Jshehai** [comment]
Hello, 
is it possible to have an update for Ryujinx too please?
Thanks in advance for your work and time :)

**Comment by MirayXS** [comment]
> Hello, 
> 
> is it possible to have an update for Ryujinx too please?
> 
> Thanks in advance for your work and time :)

He is working on it for sure I think, just wait!

**Comment by CJBok** [comment]
Updated [https://github.com/CJBok/Cheat-Tables/blob/master/Ryu%2BYuzu%20-%20Animal%20Crossing%20New%20Horizons%20v1.2.0.CT](url)
