### ISSUE TITLE
Ryujinx tables not working from version 1.0.4480

### ISSUE THREAD

**Issue by OscarOG** [CJBok/Cheat-Tables#2]
Cheat tables for Ryujinx does not work from the version 1.0.4480.

After loading the game, clicking the check box does nothing from version 1.0.448x.

Previous versions did work.

**Comment by CJBok** [comment]
Fixed: [https://github.com/CJBok/Cheat-Tables/commit/bd4ee4f42d1a9582d8ae38331f9579b454b1a7bd](url)
