### ISSUE TITLE
Remove item ID before item name

### ISSUE THREAD

**Issue by MirayXS** [CJBok/Cheat-Tables#5]
# Remove item ID before item name
## To be honest, it really annoys me that the item ID is before item name. Could you delete the ID before the item name? i can't easily search as i did before..

**Comment by MirayXS** [comment]
fixed myself.

**Comment by unwantedtomato** [comment]
Also since its for v1.2 Nature day items such as hedges and shrubs are not included. I am assuming also the new artworks too. Ironwood items like the faucet also glitch even after restarting the game.

**Comment by MirayXS** [comment]
> Also since its for v1.2 Nature day items such as hedges and shrubs are not included. I am assuming also the new artworks too. Ironwood items like the faucet also glitch even after restarting the game.

The cheats are outdated for v1.2.1 and I requested the items but he ignored
